version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: ctf_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootRDGpassword!@1
      MYSQL_DATABASE: ctf_db
    #ports:
    #  - "3306:3306"
    volumes:
      - ./db/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/db_bot/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 3

  bot:
    build: ./bot
    container_name: ctf_bot
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootRDGpassword!@1
      - DB_NAME=ctf_db
      - BOT_TOKEN=8132202680:AAFLLK9aU_zYFV9rfOkquraZpHZcM2W428U
    depends_on:
      db:
        condition: service_healthy
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

  web:
    build: ./TGBOT_site
    container_name: tgbot-marketplace
    ports:
      - "16000:5173"
    volumes:
      - ./TGBOT_site:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    restart: unless-stopped

volumes:
  db_data:
