services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rdg_db
      MYSQL_USER: rdg_ctf_user
      MYSQL_PASSWORD: rdgrdgrdg_pass
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    #ports:
    #  - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  web:
    build: .
    ports:
      - "12000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
    volumes:
      - ./app:/app
